export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const INCREMENT_ASYNC = "INCREMENT_ASYNC";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_TODOS_REQUEST = "FETCH_TODOS_REQUEST";
